INSERT INTO "public"."Ejercicios" ("id", "nombre", "descripcion", "video") VALUES ('1', 'Jab', 'El jab es el golpe más usado en el boxeo porque es muy rápido y de bajo riesgo.
Todo empieza en guardia: ligeramente de perfil, pie trasero levantado, guardia levantada, mentón hacia abajo, codos contra el cuerpo y mirada hacia el oponente.
Luego, extiende tu brazo frente a ti, girando ligeramente para que la palma de tu mano mire hacia el suelo. Mientras golpea, use sus piernas y gire sus caderas para generar más fuerza, luego regrese inmediatamente a la guardia para protegerse.
Notarás que el codo permanece alineado y no se desplaza hacia un lado. Esto es importante para tener más fuerza en el impacto.
Mantenga su mano trasera en guardia para proteger su cara. El codo trasero protege el cuerpo. Al golpear, también debe levantar ligeramente el hombro delantero para protegerse de un posible contraataque mientras el brazo delantero ya no está en guardia.
El jab no necesita ser muy poderoso para ser efectivo. Puede usarse para molestar al oponente, preparar un ataque o iniciar una secuencia.', null), ('2', 'Cross', 'El Cross es un tiro muy potente porque tiene tiempo de acelerar antes de dar en el blanco.
Extiende el brazo trasero, girando ligeramente para que la palma de la mano mire hacia el suelo.
Al golpear, ayúdate de las piernas y gira las caderas. Esta es la parte más importante del jab de brazo hacia atrás y lo que generará la potencia del golpe. Si nos centramos en los pies, el pie de atrás hace una verdadera rotación, como aplastar una colilla.
Notarás que el codo permanece alineado y no se desplaza hacia un lado. Esto es importante para tener más fuerza en el impacto. Mantenga su mano delantera en guardia para proteger su cara. El codo delantero protege el cuerpo. Al golpear, también levante ligeramente el hombro para protegerse de un posible contraataque mientras el brazo trasero ya no está en guardia.
Cuando golpees, regresa inmediatamente a la guardia para protegerte.
Este golpe es más difícil de colocar que el jab. Por lo tanto, una buena táctica es enviarlo después de un jab.', null), ('3', 'Gancho izquierdo', 'El gancho es un golpe circular destinado a evitar la defensa de tu oponente. El gancho izquierdo y derecho son muy similares.
La mayoría de la gente trata de enviar un gancho sin realmente tener un método. Estos golpes no tendrán poder. La clave estará en utilizar la rotación del busto para poner fuerza en su gancho.
Mientras golpea, gire la palma de la mano ligeramente hacia el suelo.
Al igual que con todos los demás golpes, use los hombros para protegerse de posibles contraataques. Tenga en cuenta el movimiento de las caderas y los pies. Todo el poder viene de ahí y tienes que transferir todo tu peso para realmente presionar tus tiros.
Si te enfocas en los pies, tienes que hacer una rotación real, como aplastar una colilla.', null), ('4', 'Gancho derecho', 'El gancho es un golpe circular destinado a evitar la defensa de tu oponente. El gancho izquierdo y derecho son muy similares.
La mayoría de la gente trata de enviar un gancho sin realmente tener un método. Estos golpes no tendrán poder. La clave estará en utilizar la rotación del busto para poner fuerza en su gancho.
Mientras golpea, gire la palma de la mano ligeramente hacia el suelo.
Al igual que con todos los demás golpes, use los hombros para protegerse de posibles contraataques. Tenga en cuenta el movimiento de las caderas y los pies. Todo el poder viene de ahí y tienes que transferir todo tu peso para realmente presionar tus tiros.
Si te enfocas en los pies, tienes que hacer una rotación real, como aplastar una colilla.', null), ('5', 'Gancho izquierdo al mentón', 'Un uppercut es un golpe poderoso que va de abajo hacia arriba para pasar la guardia del oponente.
Puede ser muy efectivo porque es difícil ver venir un uppercut y viene en un ángulo inusual.
Para golpear, comience desde la guardia y golpee subiendo y colocando la palma de su mano hacia su cara. Como en los otros golpes, utiliza la rotación del pecho para generar fuerza, y protégete con el hombro.
La fuerza no viene de los brazos, sino de las piernas y los abdominales.', null), ('6', 'Gancho derecho al mentón', 'Un uppercut es un golpe poderoso que va de abajo hacia arriba para pasar la guardia del oponente.
Puede ser muy efectivo porque es difícil ver venir un uppercut y viene en un ángulo inusual.
Para golpear, comience desde la guardia y golpee subiendo y colocando la palma de su mano hacia su cara. Como en los otros golpes, utiliza la rotación del pecho para generar fuerza, y protégete con el hombro.
La fuerza no viene de los brazos, sino de las piernas y los abdominales.', null), ('7', 'Deslizar', 'Para esquivar, mueva la cabeza hacia un lado para evitar el golpe de un oponente. Esta técnica consiste en doblar las rodillas y la cintura y mover la cabeza hacia un lado para evitar un golpe, en lugar de bloquearlo o desviarlo (parry).
Al esquivar, debe cronometrar su movimiento con precisión para evitar el golpe sin perder el equilibrio o la posición. Debes mover su cabeza lo suficiente para evitar el golpe, pero no tanto como para dejarte vulnerable a un contragolpe.
Esquivar es una técnica defensiva útil para evitar golpes, particularmente ganchos y derechas.
También se puede usar para crear aberturas para contragolpes, ya que el oponente pierde temporalmente el equilibrio después de lanzar un puñetazo. Esta técnica es muy eficiente, pero puede ser difícil de llevar a cabo de manera efectiva, especialmente debido al tiempo.', null), ('8', 'Bloqueo', 'El bloqueo es una técnica defensiva fundamental utilizada en el boxeo en la que un luchador usa sus brazos y manos para protegerse de los golpes de su oponente. Esta técnica implica usar los brazos para proteger la cabeza y el cuerpo de los golpes.
Para bloquear un puñetazo en la cabeza, levanta el antebrazo para cubrirte la cabeza y ponte la mano en la cara para evitar golpearte. También puede mover ligeramente la cabeza para evitar golpes que atraviesen la defensa.
Para bloquear un puñetazo al cuerpo, baje ligeramente el codo hacia el lado detrás del ataque mientras mantiene las manos en alto.
Puedes lograr esto inclinándote hacia un lado.
El bloqueo es una técnica defensiva efectiva para defenderse de una variedad de golpes, particularmente jabs y golpes directos. Sin embargo, aún recibirás el golpe y te dolerá un poco, por lo que este no debe ser tu principal medio de defensa.', null), ('9', 'Rollo', 'Esta técnica consiste en girar la parte superior del cuerpo y los hombros para deslizarse por debajo de un puñetazo y evitar recibir todo el impacto del golpe. Al rodar, debe cronometrar su movimiento con precisión para evitar el puñetazo sin perder el equilibrio o la posición.
Cambie su peso sobre el pie opuesto a la dirección en la que está girando y use sus caderas y hombros para girar la parte superior de su cuerpo bajo el golpe. También debes mantener su cabeza metida para protegerte de cualquier golpe posterior.
Algunas personas llamarán a esto ''Bajar y tejer'', y prefieren usar el término ''Rodar'' para hablar de
''Rodar los hombros''. Sin embargo, en esta aplicación, ''Rodar'' siempre significará este movimiento de rotación para pasar por debajo de los golpes. Si un ejercicio requiere un giro de hombros, se llamará explícitamente.', null), ('10', 'Parry', 'Parry es cuando usas tus manos o brazos para desviar el golpe de un oponente. Esta técnica implica usar un movimiento rápido y preciso para redirigir el golpe del oponente lejos de tu cuerpo o cabeza.
Al hacer parry, use la mano adelantada o la mano retrasada para desviar el golpe. La mano que bloquea se mueve en un movimiento diagonal o circular para redirigir el golpe, en lugar de simplemente bloquearlo.
Es importante mantener el codo cerca del cuerpo y usar un movimiento corto y brusco para desviar el golpe y evitar abrirse a un contraataque en caso de una finta.
En esta aplicación, siempre nos referiremos a ''Parry'' cuando hablemos de desviar un golpe.', null), ('11', 'Reclinarse', 'La ''inclinación hacia atrás'' es una técnica defensiva utilizada en el boxeo en la que un luchador inclina la parte superior del cuerpo hacia atrás para evadir el golpe de un oponente, en particular un gancho o un golpe de derecha.
Para hacerlo, desplace su peso hacia atrás sobre el pie trasero mientras inclina la cabeza y la parte superior del cuerpo lejos del golpe que se aproxima. Al inclinarse hacia atrás, puede crear distancia entre usted y su oponente, lo que hace que sea más difícil para el oponente conectar un golpe limpio. También puede obligar a la otra persona a extenderse demasiado, abriéndose a un mostrador.
Esta técnica requiere una buena sincronización, equilibrio y coordinación, así como la capacidad de volver rápidamente a una postura ofensiva después de evadir el golpe. La inclinación hacia atrás puede ser una técnica util para el contragolpe, ya que crea una oportunidad para que el luchador le dé un puñetazo a su oponente mientras está desequilibrado.
Sin embargo, debe usarse con moderación y con precaución, ya que confiar demasiado en esta técnica puede hacer que el luchador pierda el equilibrio y sea susceptible a otros tipos de golpes.', null), ('12', 'Paso atrás', 'Dar un paso atrás es un movimiento fundamental utilizado en el boxeo que implica dar un paso hacia atrás con uno o ambos pies. En el boxeo, dar un paso atrás se usa comúnmente como una técnica defensiva para crear distancia entre el luchador y su oponente, especialmente cuando el oponente se está acercando. para dar un puñetazo o combinación. Retroceder también se puede usar para reiniciar la pelea o para crear una oportunidad para que el peleador lance su propio contraataque.
Al dar un paso atrás, es importante que mantenga el equilibrio y mantenga su peso distribuido uniformemente en ambos pies. Debe dar un paso atrás con un movimiento rápido y controlado, asegurándose de no cruzar los pies o perder el equilibrio.
Además de retroceder en línea recta, también puede retroceder en ángulo para crear una apertura para un contragolpe o para evitar un golpe y moverse a una posición más ventajosa.
Dar un paso atrás es una técnica básica de juego de pies que todos los boxeadores deben dominar para maniobrar con eficacia alrededor del ring y evitar los golpes de sus oponentes. Este es también el movimiento defensivo más intuitivo: ves venir un ataque, simplemente sal de este camino. Por supuesto, hacerlo tiene sus limites, ya que le impide hacer cualquier tipo de contraataque significativo a menos que su paso hacia atrás esté especialmente bien sincronizado y en ángulo.', null), ('13', 'Postura', 'Tu guardia o postura es la forma de pararte frente a tu oponente. No debes estar mirando hacia adelante, sino ligeramente hacia los lados para ser un objetivo más difícil de alcanzar.
Si eres diestro, adelanta la pierna izquierda. Para los zurdos, la pierna derecha está hacia adelante.
El objetivo es tener tu mano más fuerte en la parte trasera.
Mantenga los pies separados un poco más que el ancho de los hombros para mantenerse estable.
Mantenga el talón de su espalda hacia arriba para una mayor movilidad. Levante las manos a la altura de los ojos o la barbilla, cierre los puños y manténgalos muy cerca de la cara. Baje la cabeza y mantenga los hombros elevados para protegerse. Mantenga los codos pegados a los costados. El objetivo aquí es mantenerlo compacto.
Hay otros tipos de guardias que descubriremos más adelante, pero este es perfecto para principiantes.
Una vez que estés estable, lo mejor es seguir moviéndote para ser un objetivo difícil de alcanzar.
Mientras se mueve, es necesario evitar que sus pies no se crucen o estén en la misma línea, ya que esto lo haría inestable.
Para evitar esto, debes moverte de cierta manera: para avanzar, el pie delantero se mueve primero.
Para dar un paso atrás, el pie delantero se mueve primero. Para ir a la derecha, el pie derecho se mueve primero. Para ir a la izquierda, el pie izquierdo se mueve primero. Es crucial mantenerse estable mientras se mueve a riesgo de perder el equilibrio y estar abierto al ataque.', null), ('14', 'Movimientos', 'No permanecer en el mismo lugar hace que sea más difícil golpearte, crea aperturas y conduce a un mejor entrenamiento cuando practicas boxeo de sombra. Hay muchas formas de moverse, por ahora nos centraremos en la básica principal.
Cuando te muevas, asegurate de nunca cruzar las piernas. Para lograrlo, debes moverte de una determinada manera.
Para avanzar, primero se mueve el pie adelantado.
Para retroceder, primero se mueve el pie trasero.
Para ir a la derecha, primero se mueve el pie derecho.
Para ir a la izquierda, primero se mueve el pie izquierdo.
En el boxeo, el juego de pies es la base de una defensa, un ataque y un control del ring efectivos. Al dominar el juego de pies básico, un luchador puede evitar golpes, asestar golpes más limpios y superar en maniobras a sus oponentes.', null), ('15', 'Pivote', 'Pivotar en el boxeo es una habilidad fundamental que te ayuda a crear ángulos, evitar golpes y posicionarte para contraataques efectivos. Para empezar, debes comprender que pivotar implica girar sobre el metatarso de un pie mientras mantienes una postura equilibrada y controlada.
Comienza en la postura de boxeo con los pies separados a la anchura de los hombros. Si eres ortodoxo, el pie izquierdo estará adelante y el derecho atrás. Para pivotar hacia la izquierda, presiona ligeramente con el metatarso del pie delantero y deja que el pie trasero describa un pequeño arco. Mantén el peso equilibrado sobre el pie adelantado y la guardia para protegerte en todo momento.
Al pivotar hacia la derecha, el movimiento se invierte. Impulsa ligeramente con el pie trasero y deja que el pie delantero gire alrededor del metatarso. Nuevamente, concentrate en mantener el equilibrio y los pies ligeros. Esto te permite ajustar rápidamente tu postura sin perder el control ni exponerte a golpes.
Practicar pivoteos lentos es clave. Empieza girando 90 grados en ambas direcciones para familiarizarte con el movimiento. A medida que mejores, intenta combinar los pivotes con golpes básicos como un jab o un cruzado. Por ejemplo, lanza un jab, gira y restablece inmediatamente la postura. Esto te ayudará a integrar el pivote en tus estrategias ofensivas y defensivas.
Recuerda que pivotar no se trata de saltar ni de hacer grandes movimientos. Es un ajuste sutil que mejora tu posicionamiento y te hace impredecible. Dominarlo te convertirá en un boxeador más efectivo y eficiente.', null), ('16', 'Apuntando al cuerpo', 'Los golpes al cuerpo son herramientas poderosas que pueden desgastar a tu oponente con el tiempo o incluso provocar un KO.
Si se apunta al torso, se interrumpe la respiración y se reduce la resistencia del oponente. Si se impacta en el hígado, puede ser un KO instantáneo, ya que es un golpe muy doloroso.
Al lanzar un golpe al cuerpo, flexiona ligeramente las rodillas y usa las caderas para generar potencia. Manten la guardia alta para proteger la cabeza al dar el golpe. En general, se aplican las mismas pautas a los golpes al cuerpo.
Los golpes al cuerpo son menos predecibles y pueden tomar a tu oponente desprevenido, creando oportunidades para golpes a la cabeza.
Son esenciales para una estrategia de ataque integral y pueden ser la clave para derribar a un oponente duro.', null), ('17', 'Doblando los golpes', 'Aunque golpear varias veces desde el mismo lado no se siente tan fluido como una combinación clásica de uno-dos, es una forma efectiva de cambiar el ritmo, sorprender a tu oponente y crear oportunidades.
Si siempre alternas golpes, te volverás predecible y fácil de contraatacar. Por ejemplo, puedes lanzar el mismo golpe dos veces, como un jab doble. También puedes variar la intensidad, yendo a la cabeza y luego al cuerpo, o al cuerpo y luego a la cabeza.
La clave para ser efectivo al duplicar golpes es recargar el golpe volviendo a la guardia y activando las caderas de nuevo. Si no lo haces, notarás rápidamente que a tu segundo golpe le falta potencia.', null), ('18', 'Fintas', 'Lanzar fintas en boxeo es una técnica que consiste en fingir un ataque para confundir o interrumpir al oponente.
Ten en cuenta que si la aplicación indica ''Fint
Left'', significa fingir un golpe con la mano izquierda. Si indica ''Fint Body'', significa fingir un golpe al cuerpo.
El objetivo de una finta es provocar una reacción, lo que te permite comprender sus tendencias defensivas y abrir oportunidades para ataques reales. Las fintas son movimientos sutiles que imitan golpes u otras acciones, creando la ilusión de que se aproxima un ataque. Al dominar el arte de la finta, puedes manipular el ritmo del oponente, crear oportunidades y controlar el ritmo del combate.
Una clave para una finta efectiva es que sea creíble. Esto significa que tu lenguaje corporal, tu enfoque visual y tus movimientos deben asemejarse a un golpe o acción real. Por ejemplo, si fintas un jab, extiende ligeramente la mano adelantada y desplaza el peso como si estuvieras a punto de atacar por completo. Al simular el movimiento de forma convincente, tu oponente tendrá más probabilidades de reaccionar defensivamente, lo que podría crear una oportunidad para un golpe o una combinación diferente.
Las fintas funcionan mejor cuando se usan de forma impredecible. Si usas la misma finta repetidamente sin seguirla con un ataque real, tu oponente eventualmente dejará de reaccionar.
Para mantener a tu oponente en vilo, varia tus fintas y combínalas con ataques genuinos. Por ejemplo, podrías lanzar algunas fintas ligeras y luego seguir con un derechazo potente, pillando a tu oponente con la guardia baja.
La sincronización también es crucial al usar fintas. Una finta bien sincronizada puede hacer que un oponente dude o reaccione excesivamente, afectando su confianza y ritmo.
Observa los patrones y reacciones de tu oponente para calcular el momento de tus fintas cuando sea más probable que responda. Por ejemplo, si notas que tiende a bloquear o parar cuando mueves la mano adelantada, una finta en ese momento podría hacer que se defienda, permitiéndote contraatacar con un ataque diferente.
Incorporar fintas a tu estilo de boxeo requiere práctica y paciencia. Empieza practicando fintas durante el entrenamiento, observando cómo reaccionan tus compañeros de sparring y aprendiendo qué movimientos te resultan naturales. Con el tiempo, desarrollarás una intuición sobre cómo y cuándo fintar, convirtiéndolo en una parte integral de tu estrategia ofensiva y defensiva.', null);